#cloud-config

# Abschnitt für Benutzerkonfigurationen
users:
  # Benutzername
  - name: ubuntu
    # Sudo-Berechtigungen ohne Passwort
    sudo: ALL=(ALL) NOPASSWD:ALL
    # Gruppenzugehörigkeit des Benutzers
    groups: users, admin
    # Benutzerverzeichnis
    home: /home/ubuntu
    # Standard-Shell für den Benutzer
    shell: /bin/bash
    # SSH-Schlüssel für "ubuntu"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCRxx+UKiy0G8eGG6kPntVn+kTdZkSSwT8Az50JfUP/CKIuI9jZkpMm5+PYkvlr/Spy4EAq/fq61oXrc2HygZk8kLqTRrcagfYcnBTyKDBHDO67HPGZuKQI55ud2nDODfp+hbwthfGgftyqbqO827wu5ZWHlDrtUNZcrBuxGjJrlyeBhnA80mzLIVLM8o3TCpaRoW+q+IkZOaINmk6QgV0fO7pL/4u2J1J+9aSFZV1n1F8hni+cmHV17G+n7E7vt/RmXmWrV6p8OoKXAXofA32SyWoShkvjNLrk4ejKJP/iHgMovac1UGD9nBH+XKWPOKqAWmjamKRIb8g28pynslrN aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw== marcello.calisto@tbz.ch
# SSH-Passwort-Authentifizierung deaktiviert
ssh_pwauth: false

# Root-Benutzer ist nicht deaktiviert
disable_root: false

# Paketaktualisierung beim Start
package_update: true

# Zu installierende Pakete
packages:
  # Installation von Curl
  - curl
  # Installation von wget
  - wget
  